oxr:
  app:
    name: currency-converter
    id: 1d3efa34b315486aa8a86c52a5d5f365
    base: EUR
  urls:
    base: https://openexchangerates.org/api/
    latest: /latest.json
    historical: /historical/%s.json
    currencies: /currencies.json
    convert: /convert
